export const metadata = { title: "Términos y Condiciones — ARET3" };

export default function Page() {
  const CONTENT = `<p><strong>Condiciones de servicio</strong></p>
<p>Última actualización: 30 de Septiembre de 2025</p>
<p>Gracias por elegir Aret3.</p>
<p>El sitio web&nbsp;Aret3.cl&nbsp;(el "Sitio") es propiedad de Grupo Hurtado Spa, registrada en Santiago, Chile (en adelante, "Grupo Hurtado Spa"), y está operado por esta empresa. Permite a los usuarios registrarse y utilizar nuestro software, Aret3, un servicio de suscripción web que les permite planificar, modelar y desarrollar sus ideas de negocio. En estos Términos de Servicio, Aret3 se denomina ocasionalmente el "Servicio".</p>
<p>Estos Términos de Servicio («El Acuerdo») constituyen un contrato legalmente vinculante entre usted y Grupo Hurtado Spa. Por favor, revise este Acuerdo detenidamente. Al acceder al Sitio y hacer clic en el botón «Acepto» o «Iniciar mi prueba gratuita», o al utilizar el Servicio, usted acepta establecer una relación legal vinculante con Grupo Hurtado Spa; al hacerlo, queda legalmente obligado por los Términos de Servicio y la Política de Privacidad de Grupo Hurtado Spa, denominados conjuntamente como los «Términos», y se compromete a cumplirlos. La Política de Privacidad está disponible en&nbsp;https://Aret3.com/privacy-policy</p>
<p>Si representa a una organización, su aceptación de estos Términos de servicio vinculará a su organización y por la presente usted declara y garantiza que tiene la autoridad para actuar en nombre de su organización.</p>
<p>Al firmar este acuerdo, usted tiene derecho a solicitar una firma no electrónica o a recibir registros no electrónicos en la medida en que lo permita la legislación aplicable. Además, debe aceptar los Términos en su totalidad para poder acceder al Sitio, usar los Servicios (definidos a continuación) o descargar, instalar o usar el Software o el Contenido.</p>
<p>Podemos actualizar este Acuerdo o la Política de Privacidad en cualquier momento, sin previo aviso. Debe revisar este Acuerdo y la Política de Privacidad cada vez que acceda al Sitio. Su uso continuado del Sitio y/o de los Servicios se considerará una aceptación irrevocable de dichas revisiones. Antes de continuar, le recomendamos imprimir o guardar una copia local de este Acuerdo y la Política de Privacidad para sus registros. Debe consultar periódicamente la fecha de "Última actualización" en la parte superior de este documento para familiarizarse con la versión más reciente de este Acuerdo.</p>
<p>El Servicio es de pago, aunque algunos de sus servicios pueden ser gratuitos durante un periodo de prueba gratuito. Al obtener permiso para usar el Sitio, podrá acceder a su Cuenta y utilizar nuestro Servicio. Deep Blue Sea también podría enviarle boletines informativos ocasionalmente. Al usar el sitio, tenga en cuenta que, según los Términos y nuestra Política de Privacidad, Grupo Hurtado Spa podría recopilar y guardar ciertos datos personales sobre usted, así como algunos datos no personalmente identificables.&nbsp;Grupo Hurtado Spa no cederá bajo ninguna circunstancia sus datos privados a terceros con fines comerciales.</p>
<p>Le pedimos que lea atentamente estos Términos y esperamos sinceramente que disfrute utilizando nuestro Sitio y Servicios.</p>
<h3>1. Uso y registro del Servicio y del Sitio</h3>
<p>Al aceptar estos Términos, usted declara cumplir con los siguientes términos de admisibilidad. Si actúa en nombre de una empresa, acepta que cualquier usuario final o empleado de la empresa tendrá permiso para acceder al Sitio, sus servicios y utilizar el Software del Sitio con licencia adquirido o accesible de otro modo, y también deberá aceptar y cumplir con estos Términos.</p>
<p><strong>Elegibilidad:</strong></p>
<p>Usted es elegible para celebrar este acuerdo si:</p>
<ul>
<li>no se le ha prohibido de ninguna manera por ninguna autoridad competente, acto judicial o ley jurisdiccional celebrar ningún contrato legal;</li>
<li>tienes 18 años de edad o más;</li>
<li>si una persona (el Usuario) menor de dieciocho (18) años o menor de la edad de elegibilidad y capacidad legal en la jurisdicción aplicable accede y utiliza el Servicio, usted declara por la presente que es el tutor legal de la persona en cuestión, que ha leído y aceptado estos Términos y que, sujeto a estos Términos, ha aprobado el uso actual y continuo del Servicio por parte del Usuario;</li>
<li>Grupo Hurtado Spa no le ha prohibido celebrar un acuerdo con Grupo Hurtado Spa en ningún momento anterior, ni su cuenta y/o su uso del Servicio han sido obstruidos, postergados o cancelados por Grupo Hurtado Spa en ningún momento y por ningún motivo;</li>
<li>no reside en ningún estado ilegal ni está asociado de ninguna manera con una organización terrorista ni es miembro de ella;</li>
<li>usted está utilizando el Servicio y/o aceptando estos Términos en nombre de una empresa, tiene la autoridad para vincular legalmente a dicha empresa a estos Términos, y ha sido sancionado y posee los consentimientos necesarios y requeridos de dicha empresa para aceptar y estar sujeto a estos Términos en nombre de dicha empresa.</li>
</ul>
<p><strong>Sólo para uso personal:</strong></p>
<p>Puede optar por suscribirse a un Plan de Suscripción (según se define en nuestra página de precios&nbsp;https://Aret3.cl/pricing/billing&nbsp;)que le permite usar nuestro Servicio. La suscripción y su licencia asociada son exclusivamente para su uso personal y no comercial. No está permitido vender, alquilar ni distribuir la licencia ni ningún servicio relacionado, ni comercializar ni publicar la licencia ni ningún servicio relacionado a terceros.</p>
<p><strong>Uso apropiado y restringido:</strong> Solo deberá utilizar los Servicios de manera legal y de acuerdo con estos Términos, no deberá permitir que un tercero utilice los Servicios de ninguna manera, forma o modo, y no deberá:</p>
<ul>
<li>perjudicar, interferir, interrumpir o retrasar el funcionamiento de los Servicios;</li>
<li>acosar, intimidar o amenazar a cualquier persona o interrumpir las operaciones del sistema informático de cualquier manera, incluido el envío de spam, malware o mensajes no solicitados;</li>
<li>infringir o violar los derechos de una persona, incluido su derecho a la privacidad y sus derechos de propiedad intelectual; y no podrá recopilar datos privados sobre ningún usuario del Servicio sin haber recibido su consentimiento expreso;</li>
<li>utilizar medios automatizados tales como rastreadores de software, scripts o robots para recopilar, acumular o procesar datos disponibles a través del Servicio, ni exportará, extraerá, descargará o almacenará ningún Contenido, dato u otros materiales que proporcione dicho Servicio;</li>
<li>crear una base de datos, ofrecer “Software como Servicio” (SaaS) o utilizar un servicio de alojamiento o cualquier otro medio para distribuir o revender los Servicios, el Contenido u otros datos y materiales contenidos o disponibles a través de los Servicios;</li>
<li>sancionar, instigar, permitir o de cualquier manera permitir que un tercero realice cualquiera de las acciones anteriores;</li>
<li>utilizar los Servicios para cualquier propósito ilegal, poco ético o no autorizado, o cualquier propósito que pueda, de cualquier manera, a discreción de Grupo Hurtado Spa, dañar el buen nombre y la buena voluntad de Grupo Hurtado Spa.</li>
</ul>
<p>No deberá crear ningún script, software o código o componente intrusivo que sea dañino o potencialmente dañino para los Servicios, o que los perjudique, interrumpa, devalúe o agregue cualquier funcionalidad no autorizada a los mismos.</p>
<p>Esto incluye transmitir o poner a disposición en conexión con los Servicios cualquier tipo de error web, virus, gusano, caballo de Troya, bomba de tiempo, software espía o cualquier otro código de computadora, programa o archivo que pueda dañar o esté destinado a dañar o secuestrar el funcionamiento del hardware, software o equipo de telecomunicaciones de Grupo Hurtado Spa.</p>
<p><strong>Sin licencia:</strong> Salvo que se autorice explícitamente en estos Términos, se le prohíbe usar o compartir cualquier propiedad intelectual de Grupo Hurtado Spa o de sus usuarios finales.</p>
<h3>2. Información de perfil y cuenta</h3>
<p>Usted acepta y entiende que es responsable de mantener la confidencialidad de su contraseña, la cual, junto con su dirección de correo electrónico, le permite acceder a los Servicios. Dicha dirección de correo electrónico y contraseña, junto con cualquier otra información de usuario que proporcione, conforman su «Información de Perfil» y le permiten acceder a su cuenta («Cuenta»). Usted acepta proporcionar información veraz, precisa, actual y completa sobre usted, y actualizarla de inmediato si sus circunstancias cambian. No podrá falsear la información de su perfil.</p>
<p><strong>Verificación de su cuenta:</strong> Al registrarse en los Servicios, Grupo Hurtado Spa puede verificar su identidad a través de otros servicios y, según su exclusivo criterio, puede requerir datos o identificación adicionales.</p>
<p>Si se registra por correo electrónico, Grupo Hurtado Spa podrá verificar su dirección de correo electrónico enviándole una notificación electrónica. En dicha notificación, Grupo Hurtado Spa podrá incluir información o enlaces que servirán para verificar su identidad como titular de la dirección de correo electrónico. Una vez verificada su identidad, Grupo Hurtado Spa creará una cuenta registrada a su nombre.</p>
<p><strong>Protección de su cuenta:</strong> De acuerdo con la sensibilidad de los datos almacenados en el servicio y cualquier riesgo potencial para los datos involucrados en el uso del Servicio, se le solicitará que cree una contraseña y utilice dicha contraseña para acceder a su Cuenta.</p>
<p>Preservar la confidencialidad de su Cuenta, su nombre de usuario y su contraseña es su exclusiva responsabilidad. Además, acepta ser el único responsable de todas las actividades que se realicen en su Cuenta.</p>
<p><strong>Una cuenta para una persona:</strong> La política de Grupo Hurtado Spa es tener una cuenta para una persona y una persona para cada cuenta. No puede tener más de una cuenta ni permitir que otros accedan a la suya.</p>
<p>Si es una empresa o utiliza la Cuenta en nombre de una empresa, puede permitir el acceso a un empleado, y solo a un empleado, y solo cuando esa persona haya sido autorizada a acceder a la Cuenta en su nombre.</p>
<p>Por la presente, usted declara y reconoce que, a menos que nos haya notificado explícitamente lo contrario, cualquier persona que acceda o busque acceso a su cuenta de empresa tiene los consentimientos y autorizaciones necesarios y actúa en su nombre.</p>
<p>También reconoce que cualquier acto u omisión en relación con dicho uso por parte de otra persona es como si esos actos u omisiones fueran suyos y usted conserva la responsabilidad por cualquier pérdida, interrupción o daño que dicho acto u omisión pueda causar.</p>
<p><strong>Compartir las credenciales de su cuenta:</strong> tiene expresamente prohibido compartir su nombre de usuario y contraseña con cualquier otra persona o tercero.</p>
<p><strong>Notificación de abuso:</strong> Debe informar a Grupo Hurtado Spa inmediatamente, a&nbsp;contacto@aret3.clen cualquier caso que le haga tener motivos para creer que su cuenta ha sido pirateada o ya no es segura, o si ha sido informado de un uso real o posible no autorizado de su cuenta de Aret3, ya sea que dicho uso haya sido intencionado o no.</p>
<p><strong>Responsabilidad de Grupo Hurtado Spa:</strong> Sin perjuicio de cualquier restricción de responsabilidad bajo estos Términos, Grupo Hurtado Spa no será responsable en ningún caso en que usted no haya cumplido con estos estándares de seguridad. Grupo Hurtado Spa no podrá ayudarle de ninguna manera si no aplica sus directrices de seguridad, publicadas periódicamente.</p>
<h3>3. Propiedad del contenido, derechos de propiedad intelectual</h3>
<p>Todos los derechos, títulos, intereses, propiedad y derechos de propiedad intelectual sobre las marcas comerciales y el Sitio, incluyendo, entre otros, su apariencia (p. ej., texto, gráficos, imágenes, logotipos, botones, iconos y su ubicación y diseño), imágenes, vídeo, audio, datos, contenido, software y otros medios, materiales o información, excepto el Contenido del usuario, son y seguirán siendo propiedad de Grupo Hurtado Spa y sus licenciantes. El Sitio y el Servicio están protegidos por las leyes y tratados serbios e internacionales de derechos de autor, marcas comerciales y otras leyes y tratados.</p>
<p>Los “Derechos de Propiedad Intelectual” abarcan los derechos definidos y aplicables a los derechos de autor, secretos comerciales, marcas de servicio y marcas registradas. Las patentes, el know-how, derechos de propiedad intelectual similares y cualquier derecho legal, moral o ético de cualquier tipo conforme a las leyes o regulaciones de cualquier autoridad gubernamental, judicial o reguladora, nacional o extranjera, también se incluyen en el ámbito de los Derechos de Propiedad Intelectual.</p>
<p><strong>Restricciones.</strong> Salvo lo expresamente permitido en estos Términos, el Contenido no podrá utilizarse ni ponerse a disposición de terceros para ningún fin ni de ninguna manera.</p>
<p>Sujeto a los términos y condiciones de este Acuerdo, le otorgamos, durante la vigencia de este Acuerdo, un derecho personal, intransferible, no sublicencia , no exclusivo, revocable y de propósito limitado para acceder al Sitio y utilizar los Servicios que estén sujetos a una Suscripción válida.</p>
<p><strong>GRUPO HURTADO SPA NO RECLAMA LA PROPIEDAD DEL CONTENIDO, INCLUYENDO SUS IDEAS DE NEGOCIO, TEXTO, DATOS, INFORMACIÓN, IMÁGENES, FOTOGRAFÍAS, MÚSICA, SONIDO, VIDEO U OTRO MATERIAL QUE USTED INGRESE, CARGUE, TRANSMITA O ALMACENE EN SU CUENTA DE ARET3. SUS IDEAS SE MANTENDRAN SEGURAS Y CON TOTAL CONFIDENCIAL. EL PROCESO DE CIFRADO PROTEGE SUS DATOS PRIVADOS 24/7, POR LO QUE NADIE PUEDE ACCEDER A ELLOS SIN SU PERMISO.</strong></p>
<p>Todas las entradas y cargas en su cuenta Aret3 se almacenarán un mes después del vencimiento de su suscripción y luego se eliminarán de forma permanente.</p>
<p>Grupo Hurtado Spa se reserva el derecho de acceder, leer, preservar y divulgar cualquier información y Contenido que considere razonablemente necesario para: (a) cumplir con cualquier ley, regulación, proceso legal o solicitud gubernamental aplicable, (b) hacer cumplir estos Términos de servicio, incluida la investigación de posibles violaciones de los mismos, (c) detectar, prevenir o abordar de otro modo el fraude, la seguridad o los problemas técnicos (incluido, entre otros, el filtrado de correo no deseado), (d) responder a las solicitudes de soporte del Usuario, o (e) proteger los derechos, la propiedad o la seguridad de Grupo Hurtado Spa, sus Usuarios y el público.</p>
<p>Grupo Hurtado Spa solo retendrá, usará o divulgará los Datos Personales procesados ​​en nombre de sus usuarios para el propósito específico de realizar los Servicios o según lo permitan las leyes de privacidad aplicables.</p>
<p>Grupo Hurtado Spa no será responsable por el ejercicio o no ejercicio de sus derechos bajo estos Términos de Servicio.</p>
<h3>4. Funciones impulsadas por IA</h3>
<p>Aret3 puede ofrecer funciones basadas en IA que utilizan ChatGPT de OpenAI para ofrecer sugerencias, consejos o borradores de contenido. Si bien estas funciones están diseñadas para facilitar la planificación empresarial, los resultados generados por ChatGPT pueden ser inexactos, incompletos o inadecuados para su uso específico.</p>
<p>Grupo Hurtado Spa (0 “Aret3”) no ofrece garantías ni asume ninguna responsabilidad por la exactitud, fiabilidad o suficiencia legal del contenido generado por IA.&nbsp;Los usuarios son los únicos responsables de revisar, verificar y decidir cómo utilizar dicho contenido.</p>
<p>Al utilizar funciones impulsadas por IA, también reconoce que cualquier información que proporcione a ChatGPT se comparte con un servicio de terceros (OpenAI) y que Aret3 no es legalmente responsable de este intercambio de datos.</p>
<h3>5. Declaraciones y garantías del usuario</h3>
<p>Usted es el único responsable de su Contenido y de las consecuencias de subirlo, almacenarlo, transmitirlo o distribuirlo de cualquier otra forma hacia o desde su cuenta. Salvo lo establecido en este documento, Grupo Hurtado Spa no utilizará el Contenido para ningún otro fin que no sea el de prestarle el Servicio.</p>
<p>Al cargar, almacenar, transmitir o distribuir de otro modo Contenido, usted afirma, declara y garantiza que:</p>
<ul>
<li>el Contenido y cualquier uso del mismo no infringe ni infringirá: (i) ningún derecho de terceros, incluyendo ningún derecho de autor, marca registrada, patente, secreto comercial, derecho moral, derecho de privacidad, derecho de publicidad o cualquier otra propiedad intelectual o derecho de propiedad, (ii) viola ninguna ley o regulación de valores en ninguna jurisdicción, o (iii) calumnia, difama o injuria a ninguna otra persona; y</li>
<li>El Contenido no contiene virus, adware, spyware, gusanos ni ningún otro código malicioso. Quienes infrinjan los derechos de terceros podrán estar sujetos a responsabilidades penales y civiles. Grupo Hurtado Spa se reserva todos los derechos y recursos contra cualquier Usuario que infrinja estas Condiciones de Servicio. El Contenido no contiene virus, adware, spyware, gusanos ni ningún otro código malicioso. Quienes infrinjan los derechos de terceros podrán estar sujetos a responsabilidades penales y civiles. Grupo Hurtado Spa se reserva todos los derechos y recursos contra cualquier Usuario que infrinja estas Condiciones de Servicio.</li>
</ul>
<h3>6. Sin responsabilidad</h3>
<p>Grupo Hurtado Spa no será responsable de ningún daño derivado del Servicio, el Sitio, el Software o el Contenido. Esto incluye daños directos o indirectos, incidentales, singulares o inusuales, o consecuentes de cualquier tipo que afecten el uso o provoquen la imposibilidad de usar cualquiera de los elementos anteriores, incluyendo el incumplimiento del funcionamiento previsto.</p>
<p>Dichos daños incluyen la pérdida de buena voluntad, datos o ganancias, el cumplimiento o incumplimiento de estos términos, junto con cualquier acto, omisión o causa, incluidos y sin restricciones, cualquier daño que pueda surgir de la conducta de cualquier servicio de terceros.</p>
<p>En la medida en que lo permita la ley aplicable a usted y/o su uso del Servicio, Sitio o Contenido, y sin perjuicio de lo mencionado anteriormente, usted no podrá iniciar ninguna acción después de transcurrido un (1) año desde la ocurrencia de dicha causa de acción contra Grupo Hurtado Spa o cualquiera de sus empleados, directores, funcionarios, afiliados o usuarios finales por cualquier causa, incluido el incumplimiento de estos términos.</p>
<p>Las restricciones, exclusiones y exenciones de responsabilidad anteriores se aplicarán a todas las reclamaciones por daños y perjuicios, ya sea que se basen en una acción contractual, en negligencia, en una garantía, responsabilidad estricta, negligencia, agravio o de otro modo.</p>
<p>Por la presente, usted reconoce y acepta que estas restricciones de responsabilidad se acuerdan para distribuir el riesgo que comprende en parte la contraprestación por el Sitio, el Contenido o los Servicios de Grupo Hurtado Spa que se le ofrecen, y dichas restricciones se aplicarán a pesar del incumplimiento del propósito esencial de cualquier remedio limitado, e incluso en el caso de que Grupo Hurtado Spa y/o cualquier afiliado de Grupo Hurtado Spa haya sido informado de la posibilidad de dichas responsabilidades y/o daños.</p>
<p>Sin perjuicio de cualquier disposición en contrario, y sin perjuicio de las restricciones anteriores, la responsabilidad total de Grupo Hurtado Spa hacia usted no excederá los montos que pagó por un Plan de suscripción de Grupo Hurtado Spa durante los 12 meses inmediatamente anteriores a la ocurrencia de la causa de la acción.</p>
<p>Al aceptar los términos del presente documento, el usuario reconoce plenamente que Grupo Hurtado Spa y sus afiliados no ofrecen garantías en cuanto al rendimiento, la exactitud, la funcionalidad ni la idoneidad del Servicio ni del Contenido para ningún fin específico. Grupo Hurtado Spa no garantiza ni realiza interpretaciones sobre el uso, la imposibilidad de uso u operación, ni los resultados del uso del contenido disponible en el servicio.</p>
<p>El Servicio, el Sitio y el Contenido, y cualquier parte de ellos, se proporcionan "tal cual" y "según disponibilidad", sin garantías de ningún tipo, ya sean expresas o implícitas, incluidas garantías de título o de no infracción del título, o garantías implícitas relacionadas con el uso, la comerciabilidad o la idoneidad para un propósito o uso particular.</p>
<h3>7. Servicios de terceros</h3>
<p>Algunos servicios disponibles a través de Aret3 pueden ser proporcionados por terceros. En particular, el&nbsp;servicio de Redacción de Planes de Negocios&nbsp;que se ofrece en nuestro sitio web es proporcionado exclusivamente por nuestro socios externo,&nbsp;que serán debidamente notificados al cliente.</p>
<p>Grupo Hurtado Spa (o "Aret3") no controla, gestiona ni supervisa la prestación de este servicio y no asume&nbsp;ninguna responsabilidad&nbsp;por su calidad, puntualidad, precisión o resultados. Toda responsabilidad legal, garantías y obligaciones relacionadas con este servicio recaen exclusivamente en el socio externo</p>
<p>Al contratar el servicio de redacción de planes de negocios, usted reconoce y acepta que cualquier reclamo, disputa o problema que surja o esté relacionado con este servicio se dirigirá únicamente al socio externo</p>
<h3>8. Publicidad</h3>
<p>El Sitio puede mostrar anuncios, aunque Grupo Hurtado Spa no respalda ni supervisa estos anuncios o su contenido; tampoco es Grupo Hurtado Spa responsable de lo anterior, incluso en aquellos casos en que parezcan estar afiliados a Grupo Hurtado Spa.</p>
<h3>9. Modificación de estos Términos</h3>
<p>Grupo Hurtado Spa podrá modificar o cambiar estos Términos ocasionalmente, con o sin previo aviso, y dichos cambios entrarán en vigor de inmediato. Si considera que una modificación o cambio no le resulta aceptable, podrá rescindir estos Términos. Sin embargo, tenga en cuenta que los cambios realizados en estos Términos no tendrán efecto retroactivo. Por lo tanto, es importante revisar periódicamente estos Términos para comprobar si hay cambios, enmiendas o modificaciones, y se le recomienda encarecidamente que lo haga.</p>
<h3>10. Retroalimentación</h3>
<p>Usted puede, pero no está obligado a, proporcionar a Grupo Hurtado Spa aportes, sugerencias, datos, materiales y/o comentarios con respecto a los Servicios, el Software y/o el Contenido en relación con su uso de los mismos (“Comentarios”).</p>
<p>Grupo Hurtado Spa será el propietario de todos los derechos, títulos e intereses en y sobre cualquier Comentario antes mencionado, y podrá usar o incorporar dicho Comentario en los Servicios, Contenido y/o Software a su discreción.</p>
<p>Usted reconoce que cualquier idea, sugerencia, concepto, proceso o técnica (que no sea su Contenido) que nos proporcione en relación con los Servicios, el Sitio o Grupo Hurtado Spa o su negocio ('Comentarios') se convertirá en nuestra propiedad sin ninguna compensación u otra contraprestación que le debamos pagar, y lo hace por su propia voluntad y libre albedrío.</p>
<p>Podremos o no, a nuestra entera discreción, utilizar o incorporar los Comentarios (en cualquier forma o derivado que decidamos) en el Sitio, su software, servicios, documentación, productos comerciales u otros, o en cualquier versión futura o derivado de los mismos. Por la presente, usted nos cede todos los derechos a nivel mundial y a perpetuidad sobre cualquier Comentario y, según corresponda, renuncia a cualquier derecho moral.</p>
<h3>11. Pago, reembolso, actualización y degradación</h3>
<p>Al suscribirse a un Plan de Suscripción para el Contenido y los Servicios que Grupo Hurtado Spa pone a su disposición en nuestra página de precios&nbsp;(https://app.aret3.cl/billing ), deberá abonar las tarifas publicadas en el Sitio al momento de la solicitud. El pago se realizará a través de nuestro proveedor de servicios de pago externo, Transbank, y estará sujeto a sus términos de uso y políticas de privacidad. Transbank está disponible en&nbsp;https://Transbank.cl</p>
<p>Al adquirir un Plan de Suscripción, su suscripción se facturará por adelantado al inicio de cada período de facturación. Se renovará automáticamente al final del período de suscripción. Tarifas: Grupo Hurtado Spa podrá determinar, establecer o modificar ocasionalmente las tarifas mensuales y anuales, o las cuotas únicas, por el uso del Servicio.</p>
<p>El Servicio se factura por adelantado, ya sea mensual o anualmente, y no es reembolsable. No se realizarán reembolsos ni créditos por meses parciales de servicio, reembolsos por cambios a una versión superior o inferior, ni por meses no utilizados con una cuenta abierta. Para brindar igualdad de trato a todos, no se harán excepciones.</p>
<p>Todas las tarifas no incluyen impuestos, gravámenes ni aranceles impuestos por las autoridades fiscales, y usted será responsable del pago de dichos impuestos, gravámenes o aranceles. Si decide cambiar de plan, su plan actual finalizará y se le facturará el primer mes inmediatamente después de la actualización. Por defecto, al cambiar de plan, nuestro proveedor de servicios comerciales (Transbank) prorratea el coste de la suscripción.</p>
<p>Todas tus entradas en la cuenta de Aret3 se guardarán al actualizar. Cambiar a una versión inferior del Servicio podría causar la pérdida de Contenido, funciones o capacidad de tu Cuenta. Grupo Hurtado Spa no se responsabiliza por dicha pérdida.</p>
<p>Para cualquier actualización o degradación del nivel del plan, su tarjeta de crédito u otro método de pago que haya proporcionado se cargará automáticamente con la nueva tarifa en su próximo ciclo de facturación.</p>
<h3>12. Terminación</h3>
<p>Grupo Hurtado Spa puede, a su entera discreción, rescindir estos Términos, el Servicio o cualquier servicio proporcionado por él por cualquier motivo, ya sea que la rescisión se aplique a todos los usuarios o solo a usted.</p>
<p>Estos Términos podrán rescindirse por cualquier causa y sin causa justificada, incluyendo, sin restricción alguna, si Grupo Hurtado Spa considera que usted ha incumplido estos Términos o ha actuado de forma que pueda perjudicar a Grupo Hurtado Spa o a los Servicios. Grupo Hurtado Spa podrá, a su entera discreción, abstenerse de prestar los Servicios o cualquier parte de ellos, con o sin previo aviso.</p>
<p>Por la presente, usted comprende y acepta que cualquier terminación de su acceso al servicio o servicios puede aplicarse sin previo aviso, y reconoce plenamente que Grupo Hurtado Spa puede cancelar los servicios inmediatamente o eliminar su Contenido.</p>
<p>Además, Grupo Hurtado Spa no será responsable de ningún daño causado a usted o a cualquier tercero como resultado de dichos procedimientos de terminación, o al suspender o limitar de otro modo su uso de los Servicios.</p>
<p>Sin embargo, en cualquier caso, cuando Grupo Hurtado Spa rescinda estos términos por razones que no se deban a un incumplimiento de estos términos de su parte, Grupo Hurtado Spa continuará brindándole los Servicios durante el período de Suscripción que pagó o le reembolsará la parte no utilizada de sus tarifas de suscripción prepagas, según su preferencia.</p>
<h3>13. Reembolso</h3>
<p>Por la presente, usted garantiza reembolsar y eximir de responsabilidad a Grupo Hurtado Spa y a sus afiliados, directivos, directores, empleados y agentes por cualquier reclamación, daño, obligación, pérdida, responsabilidad, coste o gasto, incluyendo, entre otros, los honorarios de abogados, que surjan debido a cualquier incumplimiento de sus obligaciones y responsabilidades en virtud de estos Términos o que se relacionen con su uso o imposibilidad de usar el Servicio, el Contenido, el Software o el Sitio. Este reembolso se realizará con prontitud, de acuerdo con la solicitud de Grupo Hurtado Spa.</p>
<h3>14. Acuerdo completo</h3>
<p>Estos Términos constituyen el acuerdo completo entre Grupo Hurtado Spa y usted. Solo podrán ser revisados ​​mediante instrumento escrito. Cualquier renuncia, demora o suspensión por parte de Grupo Hurtado Spa para ejercer sus derechos no se interpretará como una modificación de dicho acuerdo.</p>
<h3>15. Asignación</h3>
<p>Grupo Hurtado Spa podrá ceder a terceros todos los derechos y obligaciones derivados de estos Términos y/o de cualquier Plan de Suscripción. Esto se aplica sin restricción alguna a una filial y/o, en caso de fusión, adquisición o venta de la totalidad o la mayor parte de sus acciones o activos, o de la parte de sus activos subyacentes a estos Términos, con o sin previo aviso. Estos términos se ajustarán en beneficio de cualquier sucesor de Grupo Hurtado Spa.</p>
<h3>16. Ley aplicable</h3>
<p>Estos términos de servicio se regirán exclusivamente por las leyes de la República de Chile sin tener en cuenta sus normas sobre conflicto de leyes, y cualquier disputa que surja de ellos se llevará exclusivamente a los tribunales del distrito de Santiago.</p>
<p>No obstante lo anterior, podremos solicitar medidas cautelares ante cualquier tribunal de jurisdicción competente.</p>
<p>Usted acepta que cualquier causa de acción que pueda tener derivada de, o relacionada con, estos Términos, debe iniciarse dentro del año siguiente a su nacimiento. De lo contrario, dicha causa de acción quedará definitivamente excluida.</p>
<h3>17. No se admite demanda colectiva</h3>
<p>Usted acepta no emprender ni participar en ninguna demanda colectiva contra Grupo Hurtado Spa y reclamar personal y exclusivamente cualquier pérdida.</p>
<h3>18. Requisitos del sistema:</h3>
<p>Aret3 funciona en la versión más reciente de los siguientes navegadores:</p>
<p>Cromo</p>
<p>Safari</p>
<p>Firefox</p>
<p>Borde</p>
<p>Aret3 requiere que las cookies y JavaScript estén habilitados para funcionar correctamente. No obstante, el Usuario tendrá derecho a deshabilitar las cookies que no sean estrictamente necesarias para la prestación de los Servicios, desactivando el uso de ciertas cookies al utilizar el Servicio.</p>
<p>Si tiene alguna pregunta, puede contactarnos por correo electrónico a&nbsp;contact@Aret3.com</p>`;
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="text-2xl font-bold text-slate-900">Términos y Condiciones</h1>
      <article className="prose prose-slate mt-6 max-w-none" dangerouslySetInnerHTML={{ __html: CONTENT }} />
    </div>
  );
}
